permalink:           pretty

title:               Conjurate
tagline:             
url:                 https://conjurate.surge.sh
baseurl:             "/"
outdated: false
year: 2020

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              Filipe Linhares
  url:               filipelinhares.com
  email:             filipelinhares@outlook.com

version:             1.0.0
github:
  repo:             https://github.com/filipelinhares/conjurate-website

highlighter: rouge
